---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: kubemark-scale-group-2a
  namespace: kube-system
spec:
  replicas: 0
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: kubemark-scale-group-2a
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: kubemark-scale-group-2a
        machine.openshift.io/cluster-api-cluster: kubemark
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
          image: docker.io/gofed/kubemark:v1.11.3-6
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
