---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: kubemark-actuator-testing-machineset
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: test-kubemark
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: test-kubemark
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
