---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: minikube-static-machine
  namespace: kube-system
  annotations:
    machine.openshift.io/static-machine: minikube
  labels:
    machine.openshift.io/cluster-api-cluster: kubemark
spec:
  providerSpec:
    value:
      apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
      kind: KubemarkMachineProviderConfig
      image: docker.io/gofed/kubemark:v1.11.3-6
  versions:
    kubelet: 1.10.1
    controlPlane: 1.10.1
