---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: kubemark-actuator-testing-machineset-red
  namespace: kube-system
  labels:
    machine.openshift.io/cluster-api-cluster: kubemark
spec:
  replicas: 1
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: test-kubemark-red
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: test-kubemark-red
        machine.openshift.io/cluster-api-cluster: kubemark
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
          image: docker.io/gofed/kubemark:v1.11.3-6
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: kubemark-actuator-testing-machineset-green
  namespace: kube-system
  labels:
    machine.openshift.io/cluster-api-cluster: kubemark
spec:
  replicas: 1
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: test-kubemark-green
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: test-kubemark-green
        machine.openshift.io/cluster-api-cluster: kubemark
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
          image: docker.io/gofed/kubemark:v1.11.3-6
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: kubemark-actuator-testing-machineset-blue
  namespace: kube-system
  labels:
    machine.openshift.io/cluster-api-cluster: kubemark
spec:
  replicas: 1
  selector:
    matchLabels:
      sigs.k8s.io/cluster-api-machineset: test-kubemark-blue
  template:
    metadata:
      labels:
        sigs.k8s.io/cluster-api-machineset: test-kubemark-blue
        machine.openshift.io/cluster-api-cluster: kubemark
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
          kind: KubemarkMachineProviderConfig
          image: docker.io/gofed/kubemark:v1.11.3-6
      versions:
        kubelet: 1.10.1
        controlPlane: 1.10.1
